security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        database_users:
            entity: { class: App\Entity\User, property: username }
        # in_memory:
        #     memory:
        #         users:
        #             test_user:
        #                 password: test_password
        #                 roles: 'ROLE_USER'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: connexion
                check_path: connexion
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /deconnexion
                target: /
    encoders:
        App\Entity\User: bcrypt

    access_control:
        # Les regles de securité
        # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
        # peuvent acceder à toutes les pages commençant par /admin
        - { path: '^/admin', roles: ROLE_ADMIN }


        
