<?php
namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProduitController extends Controller
{
    /**
     * @Route("/produit", name="produit")
     */
    public function index()
    {
        return $this->render('produit/admin_produit.html.twig', [
            'controller_name' => 'ProduitController',
        ]);
    }

    public function creationProduit(Request $request): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            
            // $file = $produit->getImage();


            // // dd($file);

            // $fileName = $this->generateUniqueFileName().'.jpg';//TODO : résoudre bug guessExtension()


            // // moves the file to the directory where brochures are stored
            // $file->move(
            //     $this->getParameter('upload_images'),
            //     $fileName
            // );

            // // updates the 'brochure' property to store the PDF file name
            // // instead of its contents
            // $produit->setImage($fileName);

            
            $em->persist($produit);
            $em->flush();

            return $this->redirectToRoute('creationProduit');
        }

        return $this->render('produit/admin_produit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
